wad: doom1.wad
model: {d: 4096, d_head: 32, scale: 4, optimize: 2}
region: {x1: 627.2, y1: -3760.0, x2: 1395.2, y2: -2800.0}
textures:
  wall: [BROWN1, BROWN144, COMPUTE2, DOOR3, DOORSTOP, LITE3, STARTAN3, STEP6, SUPPORT2]
  flat: [CEIL3_5, FLAT14, FLAT5_5, FLOOR4_8, FLOOR7_1, F_SKY1]
